only execute callback once per key for eachAttribute
hjdivad/ember-m3 pull request #1022
Opened 2021-03-06 17:47 UTC by betocantu93

Hello, I just noticed something I consider a bug, but not sure if it's actually a bug, or intended.

When `MegamorphicModel.eachAttribute` is called, the callback is executed more than once per `key` if its on multiple "buckets" i.e. `this._attributes` and `this._data`

![Screen Shot 2021-03-06 at 11 38 39](https://user-images.githubusercontent.com/9092644/110215750-0aa63100-7e71-11eb-8458-9e2ea1c9b66b.png)

2021-03-08 18:13 UTC, hjdivad requested changes

2021-03-08 18:13 UTC, hjdivad commented on addon/record-data.js
> +    Object.keys(attrs).forEach(callback, binding);
LGTM

Can you add a test for this? (e.g. local value for existing attr, trigger callback and assert the counts are correct

2021-03-14 23:32 UTC, betocantu93 commented
@hjdivad sure thing!! added :)

2021-03-15 17:13 UTC, hjdivad approved these changes

2021-03-15 17:13 UTC, merged

2021-03-15 17:13 UTC, hjdivad commented
thanks @betocantu93!

2021-03-17 16:54 UTC, hjdivad commented
released as 3.0.7