Added a test case to reproduce the 'firstObject' issue
hjdivad/ember-m3 pull request #1726
Opened 2023-02-11 00:39 UTC by larry-x-yu

Added a test case to reproduce the `firstObject` issue whereas in certain conditions, the 'firstObject' doesn't get the latest/right value from a ManagedArray/BaseRecordArray.

Initial investigation found it may be related to a change in array change notification.

2023-02-15 21:02 UTC, hjdivad requested changes
@larry-x-yu thanks for digging into this.

I pushed a couple changes

* fixed the linting issues
* changed the implementation to not rely on a heuristic
* run the tests even for non-native proxies (since the test doesn't rely on knowing that implementation detail)

can you please expand the testing assuming the changes look good to you and then we can merge + release?

2023-02-15 21:59 UTC, larry-x-yu commented on tests/unit/model/native-access/native-access-arrays-first-object-test.js
> +module(`unit/model/native-access/native-access-arrays/first-object`, function (hooks) {
The change is failing 2 test cases:
https://github.com/hjdivad/ember-m3/actions/runs/4188087639/jobs/7258802170#step:5:3635
https://github.com/hjdivad/ember-m3/actions/runs/4188087639/jobs/7258802170#step:5:3659

Let me see if I can root cause it.

2023-02-15 22:34 UTC, hjdivad commented on tests/unit/model/native-access/native-access-arrays-first-object-test.js
> +module(`unit/model/native-access/native-access-arrays/first-object`, function (hooks) {
good catch thanks. fixed.

2023-02-16 00:33 UTC, larry-x-yu commented on tests/unit/model/native-access/native-access-arrays-first-object-test.js
> +module(`unit/model/native-access/native-access-arrays/first-object`, function (hooks) {
Added more test cases.

2023-02-16 19:23 UTC, merged